name: spotisub
services:
  spotisub:
    build:
      context: .
      dockerfile: Dockerfile
      network: host
    container_name: spotisub
    env_file: .env
    image: "blastbeng/spotisub:${TAG}"
    restart: always
    volumes:
      - "./cache:/home/user/spotisub/cache"
    ports:
      - 5183:5183
    healthcheck:
      test: curl -s http://127.0.0.1:5183/api/v1/utils/healthcheck | grep -q 'Ok!' || exit 1
      interval: 30s
      retries: 20
      start_period: 30s
